eslint/typescript-eslint-parser

- lib/ast-converter.js
- package.json
> Fix: SyntaxKind code checks, update TS peerDependency ^1.7.3 (fixes #15)

- lib/ast-converter.js
- package.json
- parser.js
- tests/lib/ecma-features.js
@nzakas would be great to get your feedback on this!
**Note**: I added `lodash.unescape` as a dependency to ensure that HTML entities in JSX tags are decoded appropriately. Now that lodash is entirely modular, I felt that it was more prudent to include a micro-dependency than reinvent the wheel.
> New: Implements JSX syntax (fixes #18)

- lib/ast-converter.js
This was probably left behind during development as per discussion in
issue #29.
> Fix: Remove console logging of node.kind (fixes #29)

- README.md
> Docs: Update README to have the correct phase order.

- lib/ast-converter.js
- tests/fixtures/attach-comments/export-default-anonymous-class.result.js
- tests/fixtures/ecma-features/classes/class-accessor-properties.result.js
- tests/fixtures/ecma-features/classes/class-computed-static-method.result.js
- tests/fixtures/ecma-features/classes/class-method-named-prototype.result.js
- tests/fixtures/ecma-features/classes/class-method-named-static.result.js
- tests/fixtures/ecma-features/classes/class-one-method-super.result.js
- tests/fixtures/ecma-features/classes/class-one-method.result.js
- tests/fixtures/ecma-features/classes/class-static-method-named-prototype.result.js
- tests/fixtures/ecma-features/classes/class-static-method-named-static.result.js
- tests/fixtures/ecma-features/classes/class-static-method.result.js
- tests/fixtures/ecma-features/classes/class-static-methods-and-accessor-properties.result.js
- tests/fixtures/ecma-features/classes/class-two-computed-static-methods.result.js
- tests/fixtures/ecma-features/classes/class-two-methods-computed-constructor.result.js
- tests/fixtures/ecma-features/classes/class-two-methods-semi.result.js
- tests/fixtures/ecma-features/classes/class-two-methods-three-semi.result.js
- tests/fixtures/ecma-features/classes/class-two-methods-two-semi.result.js
- tests/fixtures/ecma-features/classes/class-two-methods.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-factory-instance-member.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-factory-instance-member.src.ts
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-factory-static-member.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-factory-static-member.src.ts
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-instance-member.src.ts
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-static-member.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-static-member.src.ts
Closes #65 
(Ignore the branch name! This PR relates to method decorators)
> New: Add method decorators to AST (fixes #65)

- lib/ast-converter.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-factory-instance-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-factory-instance-member.src.ts
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-factory-static-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-factory-static-member.src.ts
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-instance-member.src.ts
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-static-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-static-member.src.ts
We were previously just stripping `ClassProperty` nodes entirely. This PR adds support for them, and their decorators
> New: Add property decorators to AST (fixes #71)

- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-factory-instance-member.result.js
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-factory-instance-member.src.ts
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-factory-static-member.result.js
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-factory-static-member.src.ts
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-instance-member.src.ts
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-static-member.result.js
- tests/fixtures/typescript/decorators/accessor-decorators/accessor-decorator-static-member.src.ts
Added tests for accessor decorators/decorator factories.
No further logic was needed as ESTree getters and setters are just different `kind`s of `MethodDefinition`s.
> New: Add accessor decorators to AST (fixes #63)

- .gitattributes
This is to address issues for Windows uses. 
`\r\n` is twice as many characters as `\n` so test ranges are always off.
> Fix: Tests break with Windows line-endings (fixes #93)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/type-alias-declaration.result.js
I am really sorry this has now taken a 3rd PR to get right.
This adds `loc` and `range` data for the generated `VariableDeclarator` - core `indent` is currently throwing an error because `loc` is undefined
> Fix: Add loc and range data to generated VariableDeclarator node

- .travis.yml
> Build: Add Node 6.x to Travis

- .gitattributes
Since the gitattribute file was added in https://github.com/eslint/typescript-eslint-parser/pull/97, my mac has automatically had unstaged changes relating to yml files.
I have never used gitattributes before, but adding a definition for yml seems to do the trick...
> Fix: Added missing yml lf gitattribute

- tests/fixtures/typescript/decorators/method-decorators/method-decorator-factory-instance-member.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-factory-instance-member.src.ts
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/method-decorators/method-decorator-instance-member.src.ts
`readonly` became a keyword in TS 2.0, and so the coincidentally named decorator in the 2 test cases below would produce a different AST when moving from TS 1.x to TS 2.x
> Fix: Rename decorator example to avoid issue in TS 2.x (refs #105)

- tests/fixtures/typescript/basics/non-null-assertion-operator.result.js
- tests/fixtures/typescript/basics/non-null-assertion-operator.src.ts
Further information about the operator is available here: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator
No code changes are needed to support the non-null assertion operator.
This PR is into the `ts-2` branch, which is where all of the breaking changes will go, along with the updated TS `peerDependency`.
I will submit a final PR from `ts-2` to master, once all the necessary updates are merged.
NOTE: The tests will fail on `ts-2` work until https://github.com/eslint/typescript-eslint-parser/pull/107 and https://github.com/eslint/typescript-eslint-parser/pull/108 are merged because they fix broken TS 2 tests
> Chore: Added test for non-null assertion operator (refs #105)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/abstract-class-with-abstract-method.result.js
- tests/fixtures/typescript/basics/arrow-function-with-type-parameters.result.js
- tests/fixtures/typescript/basics/declare-function.result.js
- tests/fixtures/typescript/basics/declare-namespace-with-exported-function.result.js
- tests/fixtures/typescript/basics/function-with-type-parameters.result.js
- tests/fixtures/typescript/basics/function-with-types.result.js
- tests/fixtures/typescript/basics/type-alias-declaration.result.js
- tests/fixtures/typescript/basics/var-with-type.result.js
Whilst we do use TSNode.flags for some node checks, there is not actually any reason to pass them through to the converted AST when using the `deeplyCopy()` fallback. It does not currently provide any benefit, and we will always be exposed to breaking changes.
Please see #105 for additional background on why this came up
> Fix: Exclude TSNode.flags when deeplyCopy fallback is used (refs #105)

- lib/ast-converter.js
In Microsoft/TypeScript#7645, TypeScript changed the way it handles JSX tag names.
This PR updates our conversion process accordingly, and adds a couple of helper functions for checking JSX nodes.
This PR is into the `ts-2` branch, which is where all of the breaking changes will go, along with the updated TS `peerDependency`.
I will submit a final PR from `ts-2` to master, once all the necessary updates are merged.
NOTE: The tests will fail on `ts-2` work until https://github.com/eslint/typescript-eslint-parser/pull/107 is merged
> Breaking: Update JSX tagName conversion for TS 2 (refs #105)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/arrow-function-with-type-parameters.result.js
- tests/fixtures/typescript/basics/class-with-accessibility-modifiers.result.js
- tests/fixtures/typescript/basics/class-with-implements-generic-multiple.result.js
- tests/fixtures/typescript/basics/class-with-implements-generic.result.js
- tests/fixtures/typescript/basics/class-with-implements.result.js
- tests/fixtures/typescript/basics/declare-function.result.js
- tests/fixtures/typescript/basics/function-with-type-parameters.result.js
- tests/fixtures/typescript/basics/function-with-types.result.js
- tests/fixtures/typescript/basics/non-null-assertion-operator.result.js
- tests/fixtures/typescript/basics/type-alias-declaration.result.js
- tests/fixtures/typescript/decorators/class-decorators/class-decorator-factory.result.js
- tests/fixtures/typescript/decorators/class-decorators/class-decorator.result.js
- tests/fixtures/typescript/decorators/parameter-decorators/parameter-decorator-constructor.result.js
- tests/fixtures/typescript/decorators/parameter-decorators/parameter-decorator-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/parameter-decorators/parameter-decorator-decorator-static-member.result.js
- tests/fixtures/typescript/decorators/parameter-decorators/parameter-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/parameter-decorators/parameter-decorator-static-member.result.js
- tests/fixtures/typescript/namespaces-and-modules/declare-namespace-with-exported-function.result.js
- tests/fixtures/typescript/namespaces-and-modules/shorthand-ambient-module-declaration.result.js
It turns out we were never actually adding the type annotations of function parameters to the final AST. The tokens were tracked, and so this was not having any adverse effects, but it means we were lacking some information that would be needed for future rules and assertions for the TS 2.x special "typed-this" parameter.
Once this PR goes in the final TS 2.x PR (relating to that typed-this assertion) is ready to go and we can ship our first TS 2 release :shipit: 
I am sorry about the large diff, given that this is a change which affects any typed function parameters it affects 11-12 different test cases.
I have traditionally reconciled things like this by hand to minimise the noise, but I did actually run your `node tools/update-typescript-tests.js` helper this time and it seems to have …
> Fix: Add parameter type annotations to the AST (refs #105)

- package.json
It is only appropriate for us to support a minor range for TypeScript (`~`, instead of `^` for major), because of the AST changes that occur in feature releases of TS.
Also added TS as a dev dependency of the project to ensure reliable builds.
> Build: Add TS as dev-dep, only support minor range

- lib/ast-converter.js
- tests/fixtures/ecma-features/classes/class-method-named-with-space.result.js
- tests/fixtures/ecma-features/classes/class-method-named-with-space.src.js
- tests/fixtures/typescript/basics/class-with-accessibility-modifiers.result.js
Possible fix for https://github.com/eslint/typescript-eslint-parser/issues/123
When parsing typescript node we need to add an offset when there is a space between function name and parameters.
Still need to add tests. Would like to know if I'm on the right track.
> Fix: Exception thrown when space occurs after function name

- lib/ast-converter.js
- tests/fixtures/typescript/basics/export-type-alias-declaration.result.js
- tests/fixtures/typescript/basics/export-type-alias-declaration.src.ts
- tests/fixtures/typescript/basics/export-type-class-declaration.result.js
- tests/fixtures/typescript/basics/export-type-class-declaration.src.ts
- tests/fixtures/typescript/basics/export-type-function-declaration.result.js
- tests/fixtures/typescript/basics/export-type-function-declaration.src.ts
This includes:
- Fix to ast-converter, addition of fixExports function call in SyntaxKind.TypeAliasDeclaration case statement.
- Corresponding tests
> Fix: export type alias ExportNamedDeclaration node generation (fixes #134)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/async-function-with-var-declaration.result.js
- tests/fixtures/typescript/basics/async-function-with-var-declaration.src.ts
This fixes issue an where an async function would mark all variable declarations as constant. It uses the isConst and isLet functions from TypeScript compiler utilities file.
Fixes #136
> Fix: Use ts utilities function to determine variable type (#136)

- lib/ast-converter.js
- tests/fixtures/ecma-features/classes/class-with-constructor-with-space.result.js
- tests/fixtures/ecma-features/classes/class-with-constructor-with-space.src.js
The class constructor method node range can be calculated using the
node.parameters.pos variable instead of using result.range and offset.
This fixes issues with the space-before-function-paren rule in eslint.
> Fix: Calculate constructor method range using node.parameters.pos (fixes #139)

- lib/ast-converter.js
- tests/fixtures/ecma-features/modules/export-default-class.result.js
- tests/fixtures/ecma-features/modules/export-default-class.src.js
- tests/fixtures/ecma-features/modules/export-default-named-class.result.js
- tests/fixtures/ecma-features/modules/export-default-named-class.src.js
- tests/fixtures/ecma-features/modules/export-named-class.result.js
- tests/fixtures/ecma-features/modules/export-named-class.src.js
- tests/fixtures/typescript/basics/abstract-class-with-abstract-method.result.js
The range of a class body should be from the opening brace to the
closing brace. To find the opening brace the ast converter parses over
modifiers of the class declaration and assumes it is the last token
after the last node modifier. This assumption is not always true when the
class is exported. This commit ensures we only skip over modifiers
which are after the class name or heritage clause.
> Fix: Calculate range correctly when class is exported (fixes #152)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/function-with-types-assignation.result.js
- tests/fixtures/typescript/basics/function-with-types-assignation.src.ts
Adds code to process the type annotations on parameters that have assignations
> Fix: Parameter with assignation provide type annotations (fixes #146)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/function-with-object-type-without-annotation.result.js
- tests/fixtures/typescript/basics/function-with-object-type-without-annotation.src.ts
- tests/fixtures/typescript/basics/interface-without-type-annotation.result.js
- tests/fixtures/typescript/basics/interface-without-type-annotation.src.ts
- tests/fixtures/typescript/basics/type-alias-object-without-annotation.result.js
- tests/fixtures/typescript/basics/type-alias-object-without-annotation.src.ts
Typescript allows object/interface type definitions without type annotations. This commit will replace missing type annotations with null instead of trying to convert them.
> Fix: Handle object types without annotations (fixes #148)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/export-default-class-with-generic.result.js
- tests/fixtures/typescript/basics/export-default-class-with-generic.src.ts
- tests/fixtures/typescript/basics/export-default-class-with-multiple-generics.result.js
- tests/fixtures/typescript/basics/export-default-class-with-multiple-generics.src.ts
- tests/fixtures/typescript/basics/export-named-class-with-generic.result.js
- tests/fixtures/typescript/basics/export-named-class-with-generic.src.ts
- tests/fixtures/typescript/basics/export-named-class-with-multiple-generics.result.js
- tests/fixtures/typescript/basics/export-named-class-with-multiple-generics.src.ts
When a class with a generic definition is exported we must take the
type parameters into account when finding the opening brace. This
continues the fix of pull request #153 and handles the case of exporting
a class with generics. We now find the last type parameter and use the
succeeding token as the opening brace.
> Fix: Calculate range correctly when generic class is exported (fixes #152)

- lib/ast-converter.js
- tests/fixtures/basics/identifiers-double-underscore.result.js
- tests/fixtures/basics/identifiers-double-underscore.src.js
Typescript will prepend an underscore to an identifier when it starts
with two leading underscores. This causes rules to break in eslint
becuase identifiers do not match those in the source code.
> Fix: Unescape idenfitifers typescript may prepend underscore (fixes #145)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/function-with-await.result.js
The await node should have an argument property instead
of an expression property to be a valid estree node.
https://github.com/estree/estree/blob/master/es2017.md
> Fix: Await node should have argument property (fixes #160)

- lib/ast-converter.js
- tests/lib/ecma-features.js
**UPDATE**: I was able to use this PR to work around the long-standing issue with JsxText nodes outlined in #70 
The test case: `jsx/test-content` has been enabled.
------------
Based on feedback from the TypeScript team here: https://github.com/Microsoft/TypeScript/issues/13519#issuecomment-274662665
I will be looking into refactoring remaining occurrences of `ts.findNextToken` in future too
> Fix: Optimize convertTokens, treat JsxText as token (fixes #70)

- README.md
- lib/ast-converter.js
- package.json
TypeScript 2.2 is now the stable release
> Breaking: Updated supported TypeScript version to ~2.2.1 (fixes #149)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/interface-with-jsdoc.result.js
- tests/fixtures/typescript/basics/interface-with-jsdoc.src.ts
JSDoc property is not found on parsed ESTree nodes and should be
removed when parsing typescript nodes.
> Fix: Remove jsdoc node property from ts nodes (fixes #164)

- lib/ast-converter.js
- tests/lib/attach-comments.js
- tests/lib/basics.js
- tests/lib/ecma-features.js
- tests/lib/parse.js
- tests/lib/tester.js
- tests/lib/typescript.js
Some eslint plugins except tokens to have start and end properties
instead of range. This commit adds those properties and modifies
the tests to ignore start and end property.
> Fix: Add start and end propert to tokens (fixes #172)

- tests/fixtures/ecma-features/classes/class-with-constructor-parameters.result.js
- tests/fixtures/ecma-features/classes/class-with-constructor-parameters.src.js
- tests/fixtures/ecma-features/defaultParams/class-constructor.result.js
- tests/fixtures/ecma-features/defaultParams/class-constructor.src.js
- tests/fixtures/ecma-features/defaultParams/class-method.result.js
- tests/fixtures/ecma-features/defaultParams/class-method.src.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-array.result.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-array.src.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-defaults-array.result.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-defaults-array.src.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-defaults-object.result.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-defaults-object.src.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-object.result.js
- tests/fixtures/ecma-features/destructuring/class-constructor-params-object.src.js
- tests/fixtures/ecma-features/destructuring/class-method-params-array.result.js
- tests/fixtures/ecma-features/destructuring/class-method-params-array.src.js
- tests/fixtures/ecma-features/destructuring/class-method-params-defaults-array.result.js
- tests/fixtures/ecma-features/destructuring/class-method-params-defaults-array.src.js
- tests/fixtures/ecma-features/destructuring/class-method-params-defaults-object.result.js
- tests/fixtures/ecma-features/destructuring/class-method-params-defaults-object.src.js
- tests/fixtures/ecma-features/destructuring/class-method-params-object.result.js
- tests/fixtures/ecma-features/destructuring/class-method-params-object.src.js
- tests/fixtures/ecma-features/restParams/class-constructor.result.js
- tests/fixtures/ecma-features/restParams/class-constructor.src.js
- tests/fixtures/ecma-features/restParams/class-method.result.js
- tests/fixtures/ecma-features/restParams/class-method.src.js
Here is a test that has a class constructor with two parameters. 
I noticed we are missing a lot of tests for newer version of ecmascript like async/await functions. As well as tests for class methods with default parameters, deconstructed parameters, and rest parameters. 
@JamesHenry Let me know if you want me to add more tests.
> Chore: Add test for constructor with parameters

- lib/ast-converter.js
- tests/fixtures/typescript/basics/class-with-private-parameter-properties.result.js
- tests/fixtures/typescript/basics/class-with-private-parameter-properties.src.ts
- tests/fixtures/typescript/basics/class-with-protected-parameter-properties.result.js
- tests/fixtures/typescript/basics/class-with-protected-parameter-properties.src.ts
- tests/fixtures/typescript/basics/class-with-public-parameter-properties.result.js
- tests/fixtures/typescript/basics/class-with-public-parameter-properties.src.ts
- tests/fixtures/typescript/basics/class-with-readonly-parameter-properties.result.js
- tests/fixtures/typescript/basics/class-with-readonly-parameter-properties.src.ts
Includes modifications to ast-converter and corresponding tests
> Fix: Missing parameter properties info in constructors (fixes #143)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/class-with-accessibility-modifiers.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-factory-instance-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-factory-static-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-instance-member.result.js
- tests/fixtures/typescript/decorators/property-decorators/property-decorator-static-member.result.js
Type information is preserved for interface properties and object type literals, seems to just be missing on class properties.
> New: Add type annotation to class properties (fixes  #190)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/class-with-optional-properties.result.js
- tests/fixtures/typescript/basics/class-with-optional-properties.src.ts
- tests/fixtures/typescript/basics/function-with-object-type-with-optional-properties.result.js
- tests/fixtures/typescript/basics/function-with-object-type-with-optional-properties.src.ts
- tests/fixtures/typescript/basics/interface-with-optional-properties.result.js
- tests/fixtures/typescript/basics/interface-with-optional-properties.src.ts
- tests/fixtures/typescript/basics/non-null-assertion-operator.result.js
I choose to avoid storing `optional: false` to avoid a giant mess of failing tests, as undefined is false the use case still works.
> New: Mark optional parameters (fixes #186)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/arrow-function-with-type-parameters.result.js
- tests/fixtures/typescript/basics/function-with-type-parameters-with-constraint.result.js
- tests/fixtures/typescript/basics/function-with-type-parameters-with-constraint.src.ts
- tests/fixtures/typescript/basics/function-with-type-parameters.result.js
- tests/fixtures/typescript/basics/type-alias-declaration-with-constrained-type-parameter.result.js
- tests/fixtures/typescript/basics/type-alias-declaration-with-constrained-type-parameter.src.ts
- tests/fixtures/typescript/basics/type-alias-declaration.result.js
Note that Flow uses `bound` here instead of `constraint`. I decided to go with a different property because there is some differences between Flow and TS here, however I don't have anything against aligning and require the user to use other ways to distinguish Flow and TS.
> New: Store type parameter constraints (fixes #188)

- lib/ast-converter.js
- tests/fixtures/basics/new-with-member-expression.result.js
- tests/fixtures/basics/new-with-member-expression.src.js
- tests/lib/ecma-features.js
The MetaProperty node was added a couple of months ago into typescript. I think it landed in 2.2.
https://github.com/Microsoft/TypeScript/pull/12783
I have to create a identifier node for 'new' since it is not part of the typescript metaproperty node.
> Fix: Convert MetaProperty (new.target) nodes correcly (fixes #194)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/export-default-class-with-generic.result.js
- tests/fixtures/typescript/basics/export-default-class-with-multiple-generics.result.js
- tests/fixtures/typescript/basics/export-named-class-with-generic.result.js
- tests/fixtures/typescript/basics/export-named-class-with-multiple-generics.result.js
- tests/fixtures/typescript/expressions/call-expression-type-arguments.result.js
- tests/fixtures/typescript/expressions/call-expression-type-arguments.src.ts
- tests/fixtures/typescript/expressions/new-expression-type-arguments.result.js
- tests/fixtures/typescript/expressions/new-expression-type-arguments.src.ts
For prettier/prettier/issues/13 this information must be preserved in the AST.
I had no idea how to create the test so I just did what seemed reasonable but please correct me if it's wrong.
> New: Add type arguments and parameters to AST

- .eslintrc.yml
This fixes an issue when an eslintrc config file is in the parent directory that typescript-eslint-parser is installed too.
> Fix: Set root to true in eslintrc (fixes #211)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/interface-with-construct-signature-with-parameter-accessibility.result.js
- tests/fixtures/typescript/basics/interface-with-construct-signature-with-parameter-accessibility.src.ts
As pretter reprints the code from the AST, anything not in it will be gone.
So while
```
interface I {
new (public x);
}
```
is invalid TypeScript, it's no good if pretter prints that as
```
interface I {
new (x)
}
```
If you have your editor set up to format on save, the modifier will just
be gone and you'll never see the error from TypeScript and will therfore
consider it a bug.
Note that the code does not explicitly support this, I just moved the code
that supports this in constructor parameters so that it applies to any parameter.
As the code parses correctly with just missing information in the AST there
are no good way to know that the printed file will be different from the original.
So while there is no intention to support invalid TS it's easier to do that in this
case than to …
> Chore: Wrap any parameter with modifers, not just in constructors

- README.md
- package.json
- parser.js
This would be one way to address https://github.com/eslint/typescript-eslint-parser/issues/167
Still not sure how I feel about it, but thought I would stick a working example on a branch and look for feedback.
@soda0289 @eslint/eslint-team
> Update: Open TS peerDependency, warn non-supported version (fixes #167)

- Makefile.js
- Remove unused targets
- Lint parser.js
> Chore: Cleanup Makefile

- .travis.yml
We recently open up the TypeScript peerDependency requirement of this project to allow for easier experimentation of bleeding edge versions.
We have the TypeScript devDependency as a way of specifying the version of TS that this parser officially supports, but we never removed the build step which installs all peerDependencies, and so the devDependency is not being used.
Because TypeScript just released a new stable version (2.3), the build is currently failing because we have not updated the parser to support it yet.
> Chore: Remove before_script from .travis.yml (fixes #231)

- lib/ast-converter.js
- tests/fixtures/typescript/namespaces-and-modules/ambient-module-declaration-with-import.result.js
- tests/fixtures/typescript/namespaces-and-modules/ambient-module-declaration-with-import.src.ts
- tests/fixtures/typescript/namespaces-and-modules/declare-namespace-with-exported-function.result.js
I’ll probably have to fix some tests and don’t know if just choosing the name “ModuleBlock” is OK.
> Breaking: Add .body to TSModuleBlock nodes (fixes #217)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/abstract-class-with-abstract-constructor.result.js
- tests/fixtures/typescript/basics/abstract-class-with-abstract-constructor.src.ts
> Fix: Use TSAbsractMethodDefinition for abstract constructors (fixes #228)

- README.md
- lib/ast-converter.js
- package.json
> Breaking: Support TypeScript 2.3 (fixes #232)

- lib/ast-converter.js
- tests/fixtures/typescript/basics/class-with-extends-generic-multiple.result.js
- tests/fixtures/typescript/basics/class-with-extends-generic-multiple.src.ts
- tests/fixtures/typescript/basics/class-with-extends-generic.result.js
- tests/fixtures/typescript/basics/class-with-extends-generic.src.ts
- tests/fixtures/typescript/basics/class-with-mixin.result.js
- tests/fixtures/typescript/basics/class-with-mixin.src.ts
Adds the `superTypeParameters` field to the `ClassExpression`/`ClassDeclaration` AST nodes.
prettier/prettier#1422
> Fix: Support superTypeParameters (fixes #242)

- tests/fixtures/ecma-features/experimentalAsyncIteration/async-generators.result.js
- tests/fixtures/ecma-features/experimentalAsyncIteration/async-generators.src.js
- tests/fixtures/ecma-features/experimentalObjectRestSpread/property-spread.result.js
- tests/fixtures/ecma-features/experimentalObjectRestSpread/single-spread.result.js
- tests/fixtures/ecma-features/experimentalObjectRestSpread/two-spread.result.js
- tests/lib/ecma-features.js
I noticed we were missing test for object spread. Async generator support was added in typescript 2.3
> Chore: Add tests for object spread and async generator

- lib/ast-converter.js
- tests/fixtures/ecma-features/experimentalAsyncIteration/async-iterator.result.js
- tests/fixtures/ecma-features/experimentalAsyncIteration/async-iterator.src.js
This commit depends upon https://github.com/eslint/typescript-eslint-parser/pull/237. Since that PR adds tests for async generators and allows experimental ecma-features tests to run.
https://github.com/estree/estree/blob/master/experimental/async-iteration.md
> Add support async iterators

- lib/ast-converter.js
- tests/fixtures/typescript/basics/class-with-mixin.result.js
- tests/fixtures/typescript/basics/interface-extends-multiple.result.js
- tests/fixtures/typescript/basics/interface-extends-multiple.src.ts
- tests/fixtures/typescript/basics/interface-extends.result.js
- tests/fixtures/typescript/basics/interface-extends.src.ts
- tests/fixtures/typescript/basics/interface-type-parameters.result.js
- tests/fixtures/typescript/basics/interface-type-parameters.src.ts
- tests/fixtures/typescript/basics/interface-with-construct-signature-with-parameter-accessibility.result.js
- tests/fixtures/typescript/basics/interface-with-extends-type-parameters.result.js
- tests/fixtures/typescript/basics/interface-with-extends-type-parameters.src.ts
- tests/fixtures/typescript/basics/interface-with-jsdoc.result.js
- tests/fixtures/typescript/basics/interface-with-optional-properties.result.js
- tests/fixtures/typescript/basics/typed-this.result.js
This commit create an TSInterfaceDeclration and TSInterfaceBody node when converting typescript interface
> Breaking: Change how interface node gets converted (fixes #201)

- lib/ast-converter.js
- tests/fixtures/basics/instanceof.result.js
- tests/fixtures/basics/instanceof.src.js
The `BinaryExpression` created by `instanceof` does not set the operator of the node, because the keyword is missing in `TOKEN_TO_TEXT`.
This was discovered by https://github.com/prettier/prettier/issues/1480
fixes: #252
> Fix: add `instanceof` to ast-converter

- lib/ast-converter.js
- tests/fixtures/typescript/basics/export-default-class-with-multiple-generics.result.js
- tests/fixtures/typescript/basics/export-named-class-with-multiple-generics.result.js
- tests/fixtures/typescript/basics/function-with-type-parameters-that-have-comments.result.js
- tests/fixtures/typescript/basics/function-with-type-parameters-that-have-comments.src.ts
Before:
```ts
function compare</*comment*/T,    U>() {}
//               ~~~~~~~~~~~~ TypeParameter T
//                            ~~~~~ TypeParameter U
```
After:
```ts
function compare</*comment*/T,    U>() {}
//                          ~ TypeParameter T
//                                ~ TypeParameter U
```
> Fix type parameter start location calculation

- lib/ast-converter.js
- tests/fixtures/typescript/basics/abstract-class-with-abstract-method.result.js
- tests/fixtures/typescript/basics/abstract-class-with-optional-method.result.js
- tests/fixtures/typescript/basics/class-with-mixin.result.js
- tests/fixtures/typescript/basics/export-type-function-declaration.result.js
- tests/fixtures/typescript/basics/function-with-types-assignation.result.js
- tests/fixtures/typescript/basics/interface-with-construct-signature-with-parameter-accessibility.result.js
- tests/fixtures/typescript/basics/interface-with-generic.result.js
- tests/fixtures/typescript/basics/interface-with-generic.src.ts
- tests/fixtures/typescript/basics/interface-with-jsdoc.result.js
- tests/fixtures/typescript/basics/interface-with-optional-properties.result.js
- tests/fixtures/typescript/basics/nested-type-arguments.result.js
- tests/fixtures/typescript/basics/type-alias-declaration-with-constrained-type-parameter.result.js
- tests/fixtures/typescript/basics/type-alias-declaration.result.js
- tests/fixtures/typescript/basics/typed-this.result.js
- tests/fixtures/typescript/namespaces-and-modules/declare-namespace-with-exported-function.result.js
The `deeplyCopy` function does a great job of supporting strange TS nodes however I run in to a few where it would have been nice if it had normalized type arguments and type parameters just as for "supported" nodes.
The nodes in question are
For type arguments:
- TSConstructorType
- TSFunctionType
- TSTypeReference
For type parameters:
- TSCallSignature
- TSConstructSignature
Now this do break some tests because previously such nodes were outputted as they appeared in the TypeScript AST and is therefore a breaking change. If this actually breaks anyone though is harder to tell, as far as I understand there aren't many TS specific Eslint rules around which could have been using these props. I have not updated any tests yet so you can see the breakage in the Travis logs.
Alternatives for …
> Breaking: Normalzie type parameters (fixes #197)

- README.md
This commit updates the README with a list of known issues with ESLint rules and plugins.
@JamesHenry I think by providing a list of known issues with this parser we can help new users get started and cut back on duplicate issues. I don't mind when people open issues on failing rules or plugins as it helps determine the work needed to make the parser fully support eslint. Do you think this is a worth while change or might be better served by documentation?
@corbinu @mattdell  @flying-sheep Did I miss any known issues with this parser and eslint?
> Chore: Update README with list of known issues

- lib/node-utils.js
- tests/fixtures/comments/jsx-block-comment.result.js
- tests/fixtures/comments/jsx-tag-comments.result.js
- tests/fixtures/ecma-features/jsx/self-closing-tag-inside-tag.result.js
- tests/lib/ecma-features.js
We used to use the method `getStart()` to calculate the starting range for JSXText tokens. This would skip over whitespace and cause the value of these tokens to be empty. This would also result in the range and starting line number and column to be incorrect. This commit uses the method `getFullStart()`, on JSXText tokens, which does not skip over whitespace and allows for the correct range, value and loc to be set.
This also fixes issues with JSX indentation in the new indent rule and in the eslint-plugin-react.
> Fix: Use correct starting range and loc for JSXText tokens (fixes #227)

- lib/convert.js
- tests/fixtures/comments/jsx-block-comment.result.js
- tests/fixtures/comments/jsx-tag-comments.result.js
- tests/fixtures/ecma-features/jsx/self-closing-tag-inside-tag.result.js
I ony fixed the JSXText tokens in my last commit. The Literal node needs to be fixed to use the correct range and line number. This fixes more issue with eslint-plugin-react rules
> Fix: Convert range and line number corretly in JSX literals

- lib/convert.js
- tests/fixtures/typescript/basics/class-with-optional-computed-property.result.js
- tests/fixtures/typescript/basics/class-with-optional-computed-property.src.ts
- tests/fixtures/typescript/basics/class-with-optional-property-undefined.result.js
- tests/fixtures/typescript/basics/class-with-optional-property-undefined.src.ts
I moved the optional property logic to each parent node instead of trying to figure it out in the Identifier node.
> Fix: Only set optional property on certain node property (fixes #289)

- lib/ast-node-types.js
- lib/convert.js
- lib/node-utils.js
- tests/fixtures/typescript/basics/export-type-class-declaration.result.js
- tests/fixtures/typescript/basics/function-with-object-type-with-optional-properties.result.js
- tests/fixtures/typescript/basics/function-with-object-type-without-annotation.result.js
- tests/fixtures/typescript/basics/interface-with-all-property-types.result.js
- tests/fixtures/typescript/basics/interface-with-all-property-types.src.ts
- tests/fixtures/typescript/basics/interface-with-construct-signature-with-parameter-accessibility.result.js
- tests/fixtures/typescript/basics/interface-with-jsdoc.result.js
- tests/fixtures/typescript/basics/interface-with-optional-properties.result.js
- tests/fixtures/typescript/basics/interface-without-type-annotation.result.js
- tests/fixtures/typescript/basics/type-alias-object-without-annotation.result.js
- tests/fixtures/typescript/basics/typed-this.result.js
- tests/fixtures/typescript/errorRecovery/interface-property-modifiers.result.js
- tests/fixtures/typescript/errorRecovery/interface-property-modifiers.src.ts
I noticed that optional is used twice. Once in identifier and once in the TSPropertySignature. Maybe we should clean that up.
Here is what this produces:
https://github.com/eslint/typescript-eslint-parser/issues/262#issuecomment-299722772
> Breaking: Convert Signature types to be more ESTree like (fixes #262)

- README.md
- lib/node-utils.js
- tests/fixtures/typescript/namespaces-and-modules/declare-namespace-with-exported-function.result.js
- tests/fixtures/typescript/namespaces-and-modules/module-with-default-exports.result.js
- tests/fixtures/typescript/namespaces-and-modules/module-with-default-exports.src.ts
We currently do not rename the import node type in modules. Also we do not rename all the export statement types, only ones that are used to export functions or variables. Named exports or export all statements are not converted. I think it makes more sense to follow the ESTree spec as it allows for eslint rules in the eslint-plugin-import to work correctly.
> Breaking: Use ESTree export node types in modules (fixes# 263)

- .travis.yml
Node 8 is now the current stable version, and we should be testing against it
> Chore: Add node 8 to .travis.yml

- lib/ast-node-types.js
- lib/convert.js
- lib/node-utils.js
- tests/fixtures/typescript/basics/null-and-undefined-type-annotations.src.ts
- tests/lib/__snapshots__/typescript.js.snap
I went for the simplest possible solution for now to resolve https://github.com/JamesHenry/tsep-babylon-test/issues/16.
Another awkward one in terms of Breaking vs Fix, but Fix feels ok here.
> Fix: Use TSNullKeyword for null type instead of Literal

- lib/ast-node-types.js
- lib/convert.js
- tests/fixtures/typescript/basics/export-assignment.src.ts
- tests/lib/__snapshots__/typescript.js.snap
I used the `TSExportAssignment` node with an expression property to match babylon's current behavior.
> Fix: Use TSExportAssignment node type (fixes #304)

- lib/convert.js
- tests/fixtures/jsx/element-keyword-name.src.js
- tests/lib/__snapshots__/jsx.js.snap
Typescript doesn't always use JSXIdentifier token type for tag names, we must set it manually.
> Fix: Ensure JSX tag names are JSXIdentifiers (fixes #315)

- lib/convert.js
- tests/fixtures/typescript/basics/type-parameters-comments.src.ts
- tests/lib/__snapshots__/typescript.js.snap
The next token of the last type parameter should always be the greater than token. Its end property should be the end range of the type parameter declaration.
> Fix: Calculate correct type parameter range (fixes #316)

- README.md
- lib/ast-node-types.js
- lib/convert.js
- package.json
- tests/fixtures/ecma-features/experimentalDynamicImport/dynamic-import.src.js
- tests/lib/__snapshots__/ecma-features.js.snap
Makes sense to keep support for 2.3 until 2.4 is stable upstream.
Fixes #321.
> New: Support TypeScript 2.4 (fixes #321)

- parser.js
- tests/lib/__snapshots__/basics.js.snap
- tests/lib/__snapshots__/comments.js.snap
- tests/lib/__snapshots__/typescript.js.snap
- tests/lib/basics.js
- tests/lib/comments.js
- tests/lib/ecma-features.js
- tests/lib/typescript.js
@soda0289 When testing whether or not this worked, I discovered that the tests were unfortunately not applying the parser config correctly in some cases (via the beforeEach). I have also fixed that as part of this PR, so there is a large diff because the snapshots were missing tokens and comments arrays
> New: Provider loggerFn option to configure logging (fixes #323)

- lib/ast-node-types.js
- lib/convert.js
- tests/fixtures/typescript/babylon-convergence/type-parameters.src.ts
- tests/lib/__snapshots__/typescript.js.snap
- tools/test-utils.js
This builds on #324, I'll rebase it after that one gets merged.
This PR addresses the difference outlined here https://github.com/JamesHenry/tsep-babylon-test/issues/10, removing the TypeAnnotation wrapper around the `constraint` of the type parameter.
I'm on a roll of discovering issues with my snapshot testing setup - we are catching thrown errors and writing them to error snapshots, but we were missing extra handling to make sure we fail the test on an unrecognised AST_NODE_TYPE, so I have addressed that by rethrowing.
> Breaking: Remove TypeAnnotation wrapper from constraint

- lib/convert.js
- tests/fixtures/typescript/basics/var-with-type.src.ts
- tests/fixtures/typescript/basics/variable-declaration-type-annotation-spacing.src.ts
- tests/lib/__snapshots__/typescript.js.snap
I changed range of Identifier nodes used in variable declaration and function parameters. Its a simple change but I might have missed something.
> Breaking: Include type annotation range for Identifiers (fixes #314)

- package.json
- tests/ast-alignment/.eslintrc.yml
- tests/ast-alignment/parse.js
- tests/ast-alignment/spec.js
- tests/ast-alignment/utils.js
@soda0289 @andy-ms
Now that the TypeScript PR has been merged into Babylon, and the effort to align on a TypeScript AST has become somewhat "official", I would like to propose that we begin formally testing AST alignment on our existing codebase.
As you know I had set up https://github.com/JamesHenry/tsep-babylon-test for this purpose, but it is already incredibly cumbersome to have to swich contexts and repos to try out ideas and make improvements.
This PR shows how testing for AST alignment could work.
I have added a new section to the `tests/` directory, with a dedicated spec runner (still using `jest`).
To run the tests, for now, you just do:
```
npm run ast-alignment-tests
```
I have not yet made them a required part of the primary testing for the repo, but we may trend towards that. …
> Chore: AST alignment testing against Babylon

- parser.js
It gets annoying when you’re trying to lint a project with lots of files. Fixes #348.
> Only warn about an unsupported TypeScript version once

- lib/node-utils.js
- package.json
- tests/ast-alignment/parse.js
- tests/ast-alignment/spec.js
- tests/fixtures/jsx/attributes.src.js
- tests/lib/__snapshots__/jsx.js.snap
As well as the bug fix in the name, this also includes an update to a fixture which contained invalid JSX. No parser (including espree) other than TypeScript was even able to parse the source so I have updated to be valid and updated its snapshot accordingly.
After doing that, I was able to successfully add it to the AST alignment tests.
> Fix: Remove start and end values from JSX tokens (fixes #341)

- lib/convert.js
- tests/lib/__snapshots__/basics.js.snap
- tests/lib/__snapshots__/comments.js.snap
- tests/lib/__snapshots__/ecma-features.js.snap
- tests/lib/__snapshots__/jsx.js.snap
- tests/lib/__snapshots__/typescript.js.snap
Tiny code change with a huge diff in snapshot data because it will affect any fixtures which have one or more newlines at the end of their source.
I found this when building out AST comparison tests against babylon.
> Fix: Include newlines at the end of source in AST (fixes #352)

- lib/convert.js
- tests/lib/__snapshots__/ecma-features.js.snap
- tests/lib/__snapshots__/typescript.js.snap
Found, developed and tested by comparing against Babylon (+ESTree plugin) AST and cross-referenced with espree results from the same code.
> Fix: Location data for methods and constructors

- lib/convert.js
- tests/lib/__snapshots__/basics.js.snap
- tests/lib/__snapshots__/comments.js.snap
- tests/lib/__snapshots__/ecma-features.js.snap
- tests/lib/__snapshots__/typescript.js.snap
This changes the way `implements`, `accessibility`  and `decorators` are applied.
When running babylon AST comparison tests, I noticed that babylon only applies the above properties if they are "truthy" (not exactly the right way to describe it but hopefully it's clear what I mean).
For example, if there is at least one decorator on a node, there will be a `decorators` array in the AST, otherwise, there will be no `decorators` property at all.
Currently in `typescript-eslint-parser`, we usually apply an empty array for the `decorators` in that case.
Before reviewing and merging this PR, I would first like to confirm that this is indeed the desired behaviour, @andy-ms?
I am personally pretty ambivalent about which makes more sense and would be keen to hear your thoughts on why you opted …
> Breaking: Only add .implements/.accessibility/.decorators if "truthy"

- tests/ast-alignment/spec.js
Very minor follow up to my last AST comparison PR. This breaks out the typescript fixtures and labels why they currently fail.
> Chore: Breakout and label TS-specific AST comparison tests

- lib/convert.js
- tests/fixtures/typescript/basics/class-with-extends-and-implements.src.ts
- tests/fixtures/typescript/basics/class-with-implements-and-extends.src.ts
- tests/lib/__snapshots__/typescript.js.snap
This allows for classes like
```ts
class ClassWithParentAndInterface implements MyInterface extends MyOtherClass {}
```
which currently do not parse the `extends` clause.
Fixes #361.
> New: Allow other orderings of implements/extends clauses (fixes #361)

- lib/ast-node-types.js
- lib/convert.js
- package.json
- tests/ast-alignment/spec.js
- tests/fixtures/typescript/basics/export-named-enum.src.ts
- tests/lib/__snapshots__/typescript.js.snap
cc @j-f1, as per my comments on the other PR, for this solution I opted for explicitly handling the `TSEnumDeclaration`, and I also wanted to make sure that we (typescript-eslint-parser and babylon) were aligned on the structure of `members`, so I have also handled `TSEnumMember`s and verified this is the case.
I don't believe the other elements from that PR were necessary to fix #345 in the end, so I left them out, but please let me know if you think I am missing something!
> Breaking: Explicitly handle TSEnumDeclaration (fixes #345)

- lib/convert.js
- package.json
- tests/fixtures/ecma-features/experimentalOptionalCatchBinding/optional-catch-binding-finally.src.js
- tests/fixtures/ecma-features/experimentalOptionalCatchBinding/optional-catch-binding.src.js
- tests/lib/__snapshots__/ecma-features.js.snap
Only change made was to support optional catch binding:
```ts
try {} catch {}
try {} catch {} finally {}
```
I've done so in the same way that babylon has done, setting `param` to `null` on the `CatchClause`.
Might want to hold out and wait for the full release?
> New: Support TypeScript 2.5 (fixes #368)

- lib/convert.js
- tests/ast-alignment/spec.js
- tests/lib/__snapshots__/typescript.js.snap
The `loc` objects in the diff are unfortunate - there are no changes to the relevant data there, it is just down to `name` being changed to `id`.
> Breaking: Handle TSModuleDeclaration and refactor (fixes #371)

- lib/convert.js
- lib/node-utils.js
- package.json
- tests/ast-alignment/parse.js
- tests/ast-alignment/spec.js
- tests/fixtures/typescript/babylon-convergence/type-parameter-whitespace-loc.src.ts
- tests/lib/__snapshots__/typescript.js.snap
- tests/lib/typescript.js
These location data points are obviously not too important to any downstream tools right now, and the changes I have made appear to better align us with `babylon` and the precendents set by `flow`
I have also aligned better with `babylon` as per discussion with Andy in another issue around the default value of many custom modifiers being `undefined`.
> Fix: Location data for typeAnnotations

- README.md
- lib/ast-node-types.js
- lib/convert.js
- package.json
- tests/ast-alignment/spec.js
- tests/fixtures/ecma-features/experimentalOptionalCatchBinding/optional-catch-binding-finally.src.js
- tests/fixtures/ecma-features/experimentalOptionalCatchBinding/optional-catch-binding.src.js
- tests/fixtures/typescript/basics/never-type-param.src.ts
- tests/lib/__snapshots__/ecma-features.js.snap
- tests/lib/__snapshots__/typescript.js.snap
NOTE: This will not be merged until TypeScript 2.5 is the stable release, but is already made available here to allow people to install it via git commit if they wish to use the TypeScript RC.
There are not technically any breaking changes in this PR currently, but the major version bump will be an important signal of intent when it comes time to release, so I have gone for `Breaking:`
> Breaking: Support TypeScript 2.5 (fixes #368) (#369)

- lib/ast-node-types.js
- tests/fixtures/typescript/basics/symbol-type-param.src.ts
- tests/lib/__snapshots__/typescript.js.snap
Context: https://github.com/prettier/prettier/issues/2851
> fix: add missing TSSymbolKeyword type

- .travis.yml
- README.md
- package.json
This will be merged once TypeScript 2.6 is the stable version, as usual.
This branch is protected, any changes that go into master before this PR gets merged will need to be merged into the `ts-2.6` branch - it cannot be rebased.
This is our usual policy with these TypeScript upgrades, because it allows users to rely on commit hashes as installable versions.
Also, as usual, we are classifying this as a breaking change (to trigger our release tool to increment the major version number) if though there are no breaking code changes in the parser, as there is no downside to doing so and it better signals intentions to users.
**Note:** The build is currently failing on Node 4 as for some reason the corresponding version of NPM is saying that `~2.6.0-rc` does not satisfy a `peerDependency` …
> Breaking: Support TypeScript 2.6 (fixes #394)

- lib/convert.js
- tests/fixtures/typescript/basics/type-reference-comments.src.ts
- tests/lib/__snapshots__/typescript.js.snap
When updating prettier to use the 9.0.0 version, I've noticed a comment is moved because the end position of the TypeInstantiation inside a TypeReference is being reported incorrectly.
If you review the two commits separately, you can notice the position change in the snapshot.
This is my first contribution here and I don't actually use TS, so let me know if I did something wrong! Thanks!
> Fix: Calculate end position of TypeInstantiation (fixes #406)

- lib/convert.js
- tests/lib/__snapshots__/typescript.js.snap
I think this is a breaking change, but feel free to correct me if I’m wrong.
Error this fixes:
```
.../node_modules/eslint/lib/rules/strict.js:220
const isBlock = node.body.type === "BlockStatement",
^
TypeError: Cannot read property 'type' of null
at enterFunction (.../node_modules/eslint/lib/rules/strict.js:220:39)
at listeners.(anonymous function).forEach.listener (.../node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach (<anonymous>)
at Object.emit (.../node_modules/eslint/lib/util/safe-emitter.js:47:38)
at NodeEventGenerator.applySelector (.../node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors (.../node_modules/eslint/lib/util/node-event-generator.js:280:22)
at NodeEventGenerator.enterNode …
```
> Breaking: Properly categorize constructors with no body

- lib/ast-node-types.js
- lib/convert.js
- lib/node-utils.js
- package.json
- tests/fixtures/typescript/basics/keyof-operator.src.ts
- tests/fixtures/typescript/basics/unique-symbol.src.ts
- tests/lib/__snapshots__/typescript.js.snap
This changes captures `TSTypeOperator` and treats it like a unary operator. It breaks `keyof foo` and adds support for `unique symbol`. The `TSTypeOperator` node's `typeAnnotation` parameter is now the `TSTypeReference`, rather than a `TSTypeAnnotation` which has a `TSTypeReference`. (more direct), this is to align with babylon. 
```diff
@@ -30,11 +30,12 @@
"start": Object {
"column": 9,
"line": 1,
},
},
-             "operator": 140,
+             "operator": "unique",
+             "prefix": true,
"range": Array [
9,
22,
],
"type": "TSTypeOperator",
@@ -43,36 +44,19 @@
"end": Object {
"column": 22,
"line": 1,
},
"start": Object {
-                   "column": 14,
+                   "column": 16,
"line": 1,
},
},
"range": Array [
-                 14,
+                 16,
22,
],
- …
```
> Breaking: Support unique symbol (fixes #426)

- lib/node-utils.js
- tests/fixtures/comments/jsdoc-comment.src.js
- tests/integration/external-fixtures/jsdoc-indent.js
- tests/integration/typescript.spec.js
- tests/lib/__snapshots__/comments.js.snap
This fixes an issue where TypeScript generates tokens for `{Type}` (for both the brackets and the Identifier `Type`), causing the indent rule in core to have some false positives. I'm assuming these tokens are generated as part of TypeScript's JS file checking and type hinting from doc blocks.
@eslint/eslint-team As an aside, could we potentially leverage this behavior for our own JSDoc parsing and validation in ESLint core? Would be nice if we could rely on a well-maintained project like TypeScript instead of doctrine, since we've been struggling to maintain that.
Maybe @JamesHenry has some idea of the feasibility of this, given your experience!
This is my first time working with this codebase or really anything TypeScript related, so please do let me know if there are better ways to …
> Fix: Remove all tokens inside comments from tokens array (fixes #422)

- lib/convert.js
- tests/ast-alignment/fixtures-to-test.js
- tests/fixtures/typescript/basics/class-with-definite-assignment.src.ts
- tests/fixtures/typescript/basics/var-with-definite-assignment.src.ts
- tests/lib/__snapshots__/typescript.js.snap
Build will fail due to this not yet supported in Babylon.
> New: Support Definite Assignment (fixes #424)

- lib/convert.js
- package.json
- tests/ast-alignment/fixtures-to-test.js
- tests/fixtures/tsx/generic-jsx-element.src.tsx
- tests/lib/__snapshots__/tsx.js.snap
Fixes #462
Refs: Microsoft/TypeScript#22415, prettier/prettier#4259
~~(Is there a `ts-2.9` branch that I can send PR to?)~~
> New: support generic JSX element (fixes #462)

- lib/convert.js
- tests/ast-alignment/fixtures-to-test.js
- tests/fixtures/typescript/errorRecovery/decorator-on-interface-declaration.src.ts
- tests/lib/__snapshots__/typescript.js.snap
This pull request fixes a bug that where decorators(invalid) on interface declarations are removed from the AST.
There was already a case where semantically invalid decorators are kept for enum declarations, so I followed the same logic for this case as well.
Looking forward to hearing your feedback.
Regards,
Related issues
https://github.com/prettier/prettier/issues/4552
> Fix: decorators removed on interface declarations (fixes #478)

- README.md
- lib/convert.js
- package.json
- tests/ast-alignment/fixtures-to-test.js
- tests/fixtures/tsx/generic-jsx-element.src.tsx
- tests/fixtures/typescript/expressions/tagged-template-expression-type-arguments.src.ts
- tests/lib/__snapshots__/tsx.js.snap
- tests/lib/__snapshots__/typescript.js.snap
As per our existing conventions, this change is marked as Breaking despite the lack of breaking code changes. This is to be explicit to users that the change is significant within their setup. Also this branch is protected as usual, so upstream master changes (if any) will need to be merged into this branch.
> Breaking: Support TypeScript 2.9

- lib/ast-converter.js
- lib/convert.js
- lib/node-utils.js
- tests/fixtures/ecma-features/classes/invalid-class-two-super-classes.src.js
- tests/lib/__snapshots__/ecma-features.js.snap
Fixes #493
Ref: prettier/prettier#2562
> Fix: error on multiple super classes (fixes #493)

- lib/ast-node-types.js
- lib/convert.js
- tests/ast-alignment/fixtures-to-test.js
- tests/lib/__snapshots__/ecma-features.js.snap
I guess this is a breaking change..
cc @JamesHenry
> Fix: Remove "Experimental" from rest and spread (fixes #428)

- .gitignore
- lib/convert.js
- lib/node-utils.js
> Fix: Replace removed API with public flags (fixes #498)

- README.md
- package.json
As per our existing conventions, this change is marked as Breaking despite the lack of breaking code changes. This is to be explicit to users that the change is significant within their setup. Also this branch is protected as usual, so upstream master changes (if any) will need to be merged into this branch.
This will only be considered for merging once TypeScript 3 is the stable release.
> Breaking: Support TypeScript 3.0

- package.json
This prevented eslint-release from running correctly for v19
> Fix: Remove lib from package.json files

- Makefile.js
Simplify Jest calls, reorder some code to avoid lint disabling, and add check for unused disable comments
> Chore: Makefile tweaks

- parser.js
Just as a short-term workaround, I figured we could re-expose the `parse` method.
Between this major version and the next, I'd want to work with eslint-plugin-import (and anyone else trying to parse files while linting) to ensure they follow the same algorithm as ESLint. Then maybe we could remove `parse` again.
> Fix: Re-expose parse method (fixes #519)

- package.json
Reverts eslint/typescript-eslint-parser#526
Adding a peer dependency requirement is a breaking change. So the plan is to revert the chore commit (this PR), cut a patch release, then re-apply the changes in a breaking commit and cut a major release.
Refs #534.
> Revert "Chore: Make ESLint a devDependency/peerDependency (fixes #523)"

- README.md
Are these options inherited from somewhere? If so, then maybe we should just mention that, and only list ones that are specific to this parser.
> Docs: add options to README

- README.md
- package.json
- parser.js
- tests/lib/__snapshots__/basics.js.snap
- tests/lib/__snapshots__/ecma-features.js.snap
- tests/lib/__snapshots__/jsx.js.snap
- tests/lib/__snapshots__/tsx.js.snap
- tests/lib/__snapshots__/typescript.js.snap
- tests/lib/basics.js
- tests/lib/comments.js
- tests/lib/ecma-features.js
- tests/lib/jsx.js
- tests/lib/tsx.js
- tests/lib/typescript.js
- tools/test-utils.js
Following up on https://github.com/JamesHenry/typescript-estree/pull/22, this updates to the latest version of typescript-estree.
Looks like it might also fix https://github.com/eslint/typescript-eslint-parser/issues/503.
I think we should remove support for `ecmaFeatures` in the options and add individual feature flags if we need them in the future (which seems unlikely). Thoughts?
> Breaking: typescript-estree v5

- .travis.yml
Now that Node v11 is officially in development, we should probably start testing it.
> Chore: test Node v11 in CI

- package.json
refs https://github.com/eslint/typescript-eslint-parser/pull/538#issuecomment-436252936
refs https://github.com/eslint/typescript-eslint-parser/issues/534
This makes `eslint` a `peerDependency` and will be batched with https://github.com/eslint/typescript-eslint-parser/pull/538 in the next major release.
> Breaking: make eslint a peerDep/devDep

- README.md
- parser.js
- tests/lib/tsx.js
This PR makes the parser setting `jsx` option by filename automatically.
- `*.ts` ... it sets `jsx: false`.
- `*.tsx` ... it sets `jsx: true`.
- Otherwise (E.g., `*.js`, not provided, etc...) ... respects the given `jsx` option.
(Edited at `2018-11-08 20:52Z`)
Fixes #517.
> Breaking: switch 'jsx' option by filename (fixes #517)

- README.md
- parser.js
- tests/lib/__snapshots__/comments.js.snap
This PR makes the parser `useJSXTextNode: true` by default because the current ESLint assumes so.
And add a note to README.md: "Please set `false` if you use this parser on ESLint v4."
> Breaking: make 'useJSXTextNode:true' by default

- analyze-scope.js
- tests/lib/scope-analysis.js
This PR fixes #550.
The `typeof file.slice` created two references `file` and `slice`, but it's incorrect. This PR makes the referencer creating only a reference `file`.
> Fix: wrong reference on TSQualifiedName (fixes #550)

- tests/fixtures/scope-analysis/enum-string.ts
- tests/lib/__snapshots__/scope-analysis.js.snap
- visitor-keys.js
fixes: #553 
fixes: https://github.com/bradzacher/eslint-plugin-typescript/issues/171
> Fix: crash in no-unused-vars when using enum

- analyze-scope.js
- package.json
- parser.js
This PR solves issue with: https://github.com/eslint/typescript-eslint-parser/issues/570
i had to upgrade `typescript-estree` to latest version with solution for https://github.com/JamesHenry/typescript-estree/issues/27
additionally lodash is no longer used in project
> Fix: issue with global augmentation when tokens are not present
